[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-Cold
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8
Inherits=Papyrus-Dark

[X-GNOME-Metatheme]
Name=Cold Night
GtkTheme=Cold Night
IconTheme=Cold Night
MetacityTheme=Cold Night
