---
:editor: "/usr/bin/nvim --cmd 'let g:user_mode=1'"
:thread_by_subject: false
:edit_signature: false
:ask_for_from: false
:ask_for_to: true
:ask_for_cc: true
:ask_for_bcc: false
:ask_for_subject: true
:account_selector: true
:confirm_no_attachments: true
:confirm_top_posting: true
:jump_to_open_message: true
:discard_snippets_from_encrypted_messages: false
:load_more_threads_when_scrolling: true
:default_attachment_save_dir: ''
:sent_source: sup://sent
:archive_sent: true
:poll_interval: 300
:wrap_width: 0
:slip_rows: 0
:col_jump: 2
:stem_language: english
:sync_back_to_maildir: true
:continuous_scroll: false
:always_edit_async: false
:accounts:
  :default:
    :name: Viktor Walter
    :email: viktor.walter@fel.cvut.cz
    :sendmail: msmtp -t --account=work --read-envelope-from
    :signature: "/home/viktor/.sup/signature"
    :gpgkey: ''
  :personal:
    :name: Viktor Walter
    :email: viktor.walter@disroot.org
    :sendmail: msmtp -t --account=personal --read-envelope-from
    :signature: ""
    :gpgkey: ''
  :outlook:
    :name: Viktor Walter
    :email: viktor_walter@outlook.com
    :sendmail: msmtp -t --account=outlook --read-envelope-from
    :signature: ""
    :gpgkey: ''
  :frivolous:
    :name: Viktor Walter
    :email: ciernobiely@gmail.com
    :sendmail: msmtp -t --account=frivolous --read-envelope-from
    :signature: ""
    :gpgkey: ''

:time_mode: 24h
