---
- !<tag:supmua.org,2006-10-01/Redwood/Maildir>
  uri: maildir:/home/viktor/mail/fel/inbox
  usual: true
  archived: false
  sync_back: true
  id: 1
  labels:
  - F
- !<tag:supmua.org,2006-10-01/Redwood/Maildir>
  uri: maildir:/home/viktor/mail/outlook/inbox
  usual: true
  archived: false
  sync_back: true
  id: 2
  labels:
  - O
- !<tag:supmua.org,2006-10-01/Redwood/Maildir>
  uri: maildir:/home/viktor/mail/outlook/inbox_oj
  usual: true
  archived: false
  sync_back: true
  id: 3
  labels:
  - Oj
- !<tag:supmua.org,2006-10-01/Redwood/Maildir>
  uri: maildir:/home/viktor/mail/gmail/inbox
  usual: true
  archived: false
  sync_back: true
  id: 4
  labels:
  - G
- !<tag:supmua.org,2006-10-01/Redwood/Maildir>
  uri: maildir:/home/viktor/mail/disroot/inbox
  usual: true
  archived: false
  sync_back: true
  id: 5
  labels:
  - D
- !<tag:supmua.org,2006-10-01/Redwood/Maildir>
  uri: maildir:/home/viktor/mail/disroot/junk
  usual: true
  archived: false
  sync_back: true
  id: 6
  labels:
  - Dj
- !<tag:supmua.org,2006-10-01/Redwood/Maildir>
  uri: maildir:/home/viktor/mail/fel_x/inbox
  usual: true
  archived: false
  sync_back: true
  id: 7
  labels:
  - Fx
- !<tag:supmua.org,2006-10-01/Redwood/MBox>
  uri: mbox:/home/viktor/.sup/sent.mbox
  usual: true
  archived: false
  id: 8
  labels:
  - SENT
