#!/bin/bash
killall conky
killall perl
pidof -x $0
for pid in $(pidof -x "$0"); do
  if [ $pid != $$ ]; then
    kill -9 $pid
  fi
done
sleep 2;
cd ~/.i3/conky/

echo "Prepare the focus protection and conky persistor;"
../i3subscribe window | while read -r event; do
  conkyWin=`xdotool search --class "conky"`;
  if [ -z "$conkyWin" ]; then
    conky -c dotconkyrc &>/dev/null &
  fi;
  echo $conkyWin | grep `xdotool getwindowfocus`;
  if [ "$?" -eq "0" ]; then i3-msg focus mode_toggle; fi;
    echo "again"
  
done
exit
