---
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/viktor/mail/fel/inbox
  usual: true
  archived: false
  sync_back: true
  id: 1
  labels:
  - F
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/viktor/mail/outlook/inbox
  usual: true
  archived: false
  sync_back: true
  id: 2
  labels:
  - O
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/viktor/mail/outlook/inbox_oj
  usual: true
  archived: false
  sync_back: true
  id: 3
  labels:
  - Oj
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/viktor/mail/gmail/inbox
  usual: true
  archived: false
  sync_back: true
  id: 4
  labels:
  - G
- !supmua.org,2006-10-01/Redwood/SentLoader {}
