-- Define your visual elements here
-- For examples, and a complete list on the possible elements and their 
-- properties, go to https://github.com/fisadev/conky-draw/
-- (and be sure to use the lastest version)
elements = {
{
    kind = 'bar_graph',
    conky_value = 'exec nvidia-smi --query-gpu="utilization.gpu" --format=csv,noheader,nounits',
    from = {x = 1406, y = 0},
    to = {x = 1406, y = 18},
    background_thickness = 8,
    bar_thickness = 8,
    bar_color = 0xFF5500,
    background_color = 0x555555,
  },
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu0',
    from = {x = 1414, y = 0},
    to = {x = 1414, y = 18},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x0055FF,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu1',
    from = {x = 1419, y = 0},
    to = {x = 1419, y = 18},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x0055FF,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu2',
    from = {x = 1424, y = 0},
    to = {x = 1424, y = 18},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x0055FF,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu3',
    from = {x = 1429, y = 0},
    to = {x = 1429, y = 18},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x0055FF,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu4',
    from = {x = 1434, y = 0},
    to = {x = 1434, y = 18},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x0055FF,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu5',
    from = {x = 1439, y = 0},
    to = {x = 1439, y = 18},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x0055FF,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu6',
    from = {x = 1444, y = 0},
    to = {x = 1444, y = 18},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x0055FF,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'cpu cpu7',
    from = {x = 1449, y = 0},
    to = {x = 1449, y = 18},
    background_thickness = 4,
    bar_thickness = 4,
    bar_color = 0x0055FF,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'memperc',
    from = {x = 1457, y = 0},
    to = {x = 1457, y = 18},
    background_thickness = 8,
    bar_thickness = 8,
    bar_color = 0x00FF55,
    background_color = 0x555555,
},
{
    kind = 'bar_graph',
    conky_value = 'swapperc',
    from = {x = 1467, y = 18},
    to = {x = 1467, y = 0},
    background_thickness = 8,
    bar_thickness = 8,
    bar_color = 0x00AAAA,
    background_color = 0x555555,
},
}
