#!/bin/bash
killall conky
cd ~/.i3/
conky -c dotconkyrc &
./i3subscribe workspace | while read -r event; do
xdotool search --class "conky" | grep `xdotool getwindowfocus`;
if [ "$?" -eq "0" ]; then i3-msg focus mode_toggle; fi
done
exit
